### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by arokem** [richford/scipy_proceedings#2]
- [x] A simulation that would not fit in pywren, but works in CK.
- [x] "Simulation" example (e.g., matrix multiply) with potentially a comparison to pywren 
- [x] MRI example (expand on the ipynb example in the docs).
- [x] ImageJ example (https://github.com/ccurtis7/diff_classifier)

**Comment by richford** [comment]
Closed with #6 and #10 and minor edits in other PRs.
